### PR TITLE
GH-242 add-module, add-command, add-option metagenerated

### PR DESCRIPTION
**Pull request by eedwardsav**
The goal of this PR was to utilize the current add-command, add-module, and add-option behavior to re-generate the stubbs files themselves.

Currently each of those commands use their own custom argument parsing, meaning there is inconsistent behavior when maintaining or managing the stubbs module using its own commands.

I re-generated add-option, add-command, and add-module using the commands themselves, along with all of the relevant options shared among these commands, ensuring I preserved the original values where appropriate.

I then manually moved the original `script` logic into each of these commands.

## point of discussion

This PR results in improved consistency between how modules generated by stubbs work, and how stubbs itself works on the command line.

**This means that interactive use can no longer be supported on these commands**, as the generate-options logic currently does not support a way to interactively prompt the user for options.

An upside to this is that it makes the rerun module itself much more automation friendly, as previously you could not force or prevent interactive dialogs in many scenarios (such as updating a previously created entry or using `--default ""` with an empty string). -- See the gist linked at the bottom.

### Two possible future approaches to address this behavior change:
1) add functionality to the actual stubbs generate-options behavior to allow both stubbs itself and module authors to leverage interactive use, this would require some level of design
2) change arguments for stubbs commands that normally have `required true` to being `required false`, and then add back the original interactive option logic after `options.sh` passes through the command line. (The downside to this is that viewing the help text would show those arguments as being optional when in fact they are required).

I believe that interactive use is 'nice to have', but by having stubbs use the same behavior that it generates, you can actually use stubbs to safely extend its own modules\commands.

This also would open up room for doing more meta programming \ bootstrapping of stubbs, such as allowing stubbs to automatically update its resources and import the 'logic' into the appropriate places from a template.

As an example, [this gist](https://gist.github.com/eedwardsav/4caaa013ebc21cd54f5f62a7e5d59610) shows how I was able to re-create the options/layout scaffold for stubbs by using itself.

### CODE REVIEW

**Comment by eedwardsav** [comment]
Note: This also includes changes from #241

**Comment by stagrlee** [comment]
This is a great clean-up getting stubbs to generate itself.  If we don't hit a circular dependency in the future, this should make stubbs maintenance much easier.  Reviewing the stubbs tests right now to see if CRUD tests would catch a regression before I thumbs up on this.

**Comment by eedwardsav** [comment]
@stagrlee 
Cool, just for clarity, due to implementation logic living inside `script` itself, re-generating commands with `--overwrite` would stomp on the implementation logic. This is why I had to first generate the new commands (in a temporary module called `stubbz`) so I could then manually copy the implementation logic into them, and then port them back into `stubbs`.

A future enhancement to support auto-regenerating could include changing the script template so that script SOURCES your implementation, rather than expecting you to actually edit the file. This way you could re-run `--overwrite` on itself, and it would only update the 'wrapping logic' while keeping your original implementation intact.

With that pattern if I wanted to update the implemention logic I could just update my implementation file and then re-run stubbs against itself.

**Comment by ahonor** [comment]
Does the -? flag still show the usage for the command? Eg,

    mymodule:command -?

**Comment by eedwardsav** [comment]
@ahonor if you're referring to the changes from #241 (which this PR includes), then **no**, I removed the help option entirely, since it is not an explicit argument and impedes passthrough (and sort of seems counter-intuitive since all other options are explicitly created using add-option)

e.g. if I want to view the help for a command I run `rerun <modulename>:` and look at the command help output for that modules commands

If we force `-?` on the command, then that means the command cannot choose to use `-?` as an explicit argument or pass it through.

By removing `-?` we allow the user to choose to implement it if they wish (e.g. I could use `add-option` to define a `short=?` and `long=help` option, and in my implementation code I could call `rerun_option_usage`, or display my own help text, or just pass it through to an underlying executable)

Thoughts?

**Comment by eedwardsav** [comment]
Okay I found an elegant solution for the help text...

I added a new option metadata field called `USAGE` which defaults to `false`.

It's an 'argless option', so it's a simple switch.

Specifying it during `add-option` will mark that option as `USAGE=true`, which means when `generate-options` runs its generator, it will cause it to execute help text for that command.

It works quite nicely and gives back help text for `add-option`, `add-command`, and `add-module` but using the actual `add-option` \ `generate-options` behavior! :)

@stagrlee  I added a functional test to cover #241 but I believe it may have surfaced a bug in generate-options so I'm investigating further

**Comment by eedwardsav** [comment]
Fixed the bug in generate-options (see last comment in #241) and added functional tests.

**Comment by stagrlee** [comment]
I'm thinking USAGE=true should be default allowing developers that need to pass through the -? to some other tool the ability to override the default helper capability of rerun.  I like having the help parameter even though 'rerun module:' is easier to type than 'rerun module: --help'

**Comment by eedwardsav** [comment]
In that case we would need to update the library to automatically generate a "help option" when making a command or module, but would need to ensure that if the user explicitly removes it from their command that we don't auto add it back. USAGE=true is metadata for an option, so defaulting to true doesn't make sense since that would cause every option to act like a help option.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by eedwardsav** [comment]
@stagrlee 

I've updated the generate options passthrough behavior to address a bug I created which would actually not pass through any options due to shifting them out.

Here's an example of an updated version of `options.sh` generated with the changes:

```
rerun_options_parse() {
  
    unrecognized_args=()

    while (( "$#" > 0 ))
    do
        OPT="$1"
        case "$OPT" in
            --recognized1) rerun_option_check $# $1; RECOGNIZED1=$2 ; shift 2 ;;
            --recognized2) rerun_option_check $# $1; RECOGNIZED2=$2 ; shift 2 ;;
            # unrecognized arguments
            *)
              unrecognized_args+=("$OPT")
              shift
              ;;
        esac
    done

    # Set defaultable options.

    # Check required options are set
    [[ -z "$RECOGNIZED1" ]] && { echo >&2 "missing required option: --recognized1" ; return 2 ; }
    [[ -z "$RECOGNIZED2" ]] && { echo >&2 "missing required option: --recognized2" ; return 2 ; }
    # If option variables are declared exportable, export them.

    # Make unrecognized command line options available in $_CMD_LINE
    if [ ${#unrecognized_args[@]} -gt 0 ]; then
      export _CMD_LINE="${unrecognized_args[@]}"
    fi
    #
    return 0
}
```

Notable changes are:

instantiate an array to capture the unrecognized arguments
```
    unrecognized_args=()
```

continue to shift out unrecognized arguments, but first add them to the array
```
            # unrecognized arguments
            *)
              unrecognized_args+=("$OPT")
              shift
              ;;
```

check if there are any unrecognized args, if so, explode the array into `_CMD_LINE`
```
    # Make unrecognized command line options available in $_CMD_LINE
    if [ ${#unrecognized_args[@]} -gt 0 ]; then
      export _CMD_LINE="${unrecognized_args[@]}"
    fi
```

**Comment by stagrlee** [comment]
Note - please review discussion for #242 

The regression tests seem to be enough to catch big problems with the refactoring in the patch so that makes review easier.

**Comment by stagrlee** [comment]
Sorry for the delay (again)...

This is what what I'm thinking the passthrough should be to preserve the help functionality of the command inside the module.

Right now its

```
            -|--*?) echo >&2 "unrecognized option: $OPT"
                rerun_option_usage
                exit 2
                ;;
```

Still print and exit, but only if you are asking for help


```
            -?|--help) echo >&2 "unrecognized option: $OPT"
                rerun_option_usage
                exit 2
                ;;
```

**Comment by eedwardsav** [comment]
@stagrlee Thanks for the feedback, Lee

I've:
- removed the `--usage` switch from `add-option`
- removed the `USAGE` metadata from options
- removed the `add-option`-generated `--help` option
- added `GENERATE_HELP` metadata to commands (similar to as in #240) which is set by...
- a `--generate-help` option to `add-command`, which defaults to `true`.

As you'll see, it now generates a help option by default, and supports both `-?` and `--help`.

Here's a quick script to test it with (run from rerun directory):

```bash
rm -rf ./modules/my-module
RERUN_MODULES=./modules ./rerun --loglevel debug stubbs: add-module --module my-module --description "my test module"
RERUN_MODULES=./modules ./rerun --loglevel debug stubbs: add-command --module my-module --command my-command --description "my test command"
RERUN_MODULES=./modules ./rerun --loglevel debug stubbs: add-option --module my-module --command my-command \
  --option "test1" \
  --description "my test option" \
  --required "true"
RERUN_MODULES=./modules ./rerun --loglevel debug stubbs: add-option --module my-module --command my-command \
  --option "test2" \
  --description "my test option 1" \
  --required "true"
  
RERUN_MODULES=./modules ./rerun --loglevel debug my-module: my-command -?
RERUN_MODULES=./modules ./rerun --loglevel debug my-module: my-command --help
```

expected output:
```bash
$ RERUN_MODULES=./modules ./rerun --loglevel debug my-module: my-command -?
usage: rerun my-module:my-command  --test1 <>  --test2 <> 
```
```bash
$ RERUN_MODULES=./modules ./rerun --loglevel debug my-module: my-command --help
usage: rerun my-module:my-command  --test1 <>  --test2 <> 
```

**Pull request merged**
